<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
    __FILE__, // Path to the current file, all other file names are relative to the directory containing this file
    'itop-sd-extension/3.1.1',
    array(
        // Identification
        //
        'label' => 'SD iTop Extension',
        'category' => 'business',

        // Setup
        //
        'dependencies' => array(
            'itop-config-mgmt/2.0.0', // Add this line
        ),
        'mandatory' => false,
        'visible' => true,

        // Components
        //
        'datamodel' => array(
            'vendor/autoload.php',
            'model.itop-sd-extension.php', // Contains the PHP code generated by the "compilation" of datamodel.itop-sd-extension.xml
        ),
        'webservice' => array(
            
        ),
        'data.struct' => array(
            // add your 'structure' definition XML files here,
        ),
        'data.sample' => array(
            // add your sample data XML files here,
        ),
        
        // Documentation
        //
        'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
        'doc.more_information' => '', // hyperlink to more information, if any 

        // Default settings
        //
        'settings' => array(
            // Module specific settings go here, if any
        ),
    )
);
?>
