<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_TwigService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public '.container.private.twig' shared service.
     *
     * @return \Twig\Environment
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Cache/CacheInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Cache/FilesystemCache.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Extension/CoreExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Extension/EscaperExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Extension/OptimizerExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Extension/StagingExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/ExtensionSet.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Template.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/TemplateWrapper.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Environment.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Loader/FilesystemLoader.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/twig-bridge/Extension/TranslationExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/twig-bridge/Extension/CodeExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/twig-bridge/Extension/RoutingExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/twig-bridge/Extension/YamlExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/twig-bridge/Extension/StopwatchExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/twig-bridge/Extension/HttpKernelExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/twig-bridge/Extension/HttpFoundationExtension.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/http-foundation/UrlHelper.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Extension/GlobalsInterface.php';
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/Twig/AppGlobal.php';
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/Twig/AppVariable.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/twig-bridge/AppVariable.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/RuntimeLoader/RuntimeLoaderInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/RuntimeLoader/ContainerRuntimeLoader.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/twig-bundle/DependencyInjection/Configurator/EnvironmentConfigurator.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/http-kernel/Debug/FileLinkFormatter.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/stopwatch/Stopwatch.php';
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/Twig/AppExtension.php';

        $a = new \Twig\Loader\FilesystemLoader([], (\dirname(__DIR__, 5).'/env-production/itop-portal-base/portal'));
        $a->addPath((\dirname(__DIR__, 5).'/env-production/'));

        $container->services['.container.private.twig'] = $instance = new \Twig\Environment($a, ['debug' => false, 'strict_variables' => false, 'autoescape' => 'name', 'cache' => ($container->targetDir.''.'/twig'), 'charset' => 'UTF-8']);

        $b = ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));
        $c = new \Symfony\Bridge\Twig\AppVariable();
        $c->setEnvironment('prod');
        $c->setDebug(false);
        if ($container->has('request_stack')) {
            $c->setRequestStack($b);
        }

        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\TranslationExtension(NULL));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\CodeExtension(($container->privates['debug.file_link_formatter'] ?? ($container->privates['debug.file_link_formatter'] = new \Symfony\Component\HttpKernel\Debug\FileLinkFormatter(NULL))), (\dirname(__DIR__, 5).'/env-production/itop-portal-base/portal'), 'UTF-8'));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\RoutingExtension(($container->services['url_generator'] ?? $container->getUrlGeneratorService())));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\YamlExtension());
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\StopwatchExtension(($container->privates['debug.stopwatch'] ?? ($container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))), false));
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpKernelExtension());
        $instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpFoundationExtension(new \Symfony\Component\HttpFoundation\UrlHelper($b, ($container->privates['router.request_context'] ?? $container->getRouter_RequestContextService()))));
        $instance->addExtension(($container->privates['Combodo\\iTop\\Portal\\Twig\\AppExtension'] ?? ($container->privates['Combodo\\iTop\\Portal\\Twig\\AppExtension'] = new \Combodo\iTop\Portal\Twig\AppExtension())));
        $instance->addExtension(new \Combodo\iTop\Portal\Twig\AppGlobal(($container->privates['Combodo\\iTop\\Portal\\EventListener\\UserProvider'] ?? $container->getUserProviderService())));
        $instance->addGlobal('app', new \Combodo\iTop\Portal\Twig\AppVariable($c, $container));
        $instance->addRuntimeLoader(new \Twig\RuntimeLoader\ContainerRuntimeLoader(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => ['privates', 'twig.runtime.httpkernel', 'getTwig_Runtime_HttpkernelService', true],
        ], [
            'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => '?',
        ])));
        (new \Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator('F j, Y H:i', '%d days', NULL, 0, '.', ','))->configure($instance);

        return $instance;
    }
}
