<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H0IrwYyService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.h0IrwYy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h0IrwYy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'brick_collection' => ['services', 'brick_collection', 'getBrickCollectionService', true],
            'brick_controller_helper' => ['services', 'brick_controller_helper', 'getBrickControllerHelperService', true],
            'browse_brick' => ['services', 'browse_brick', 'getBrowseBrickService', true],
            'context_manipulator' => ['services', 'context_manipulator', 'getContextManipulatorService', true],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'lifecycle_validator' => ['services', 'lifecycle_validator', 'getLifecycleValidatorService', true],
            'navigation_rule_helper' => ['services', 'navigation_rule_helper', 'getNavigationRuleHelperService', true],
            'object_form_handler' => ['services', 'object_form_handler', 'getObjectFormHandlerService', true],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_manipulator' => ['services', 'request_manipulator', 'getRequestManipulatorService', true],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'url_generator', 'getUrlGeneratorService', false],
            'scope_validator' => ['services', 'scope_validator', 'getScopeValidatorService', true],
            'security_helper' => ['services', 'security_helper', 'getSecurityHelperService', true],
            'session' => ['privates', '.session.deprecated', 'get_Session_DeprecatedService', true],
            'session_message_helper' => ['services', 'session_message_helper', 'getSessionMessageHelperService', true],
            'twig' => ['services', '.container.private.twig', 'get_Container_Private_TwigService', true],
            'ui_extensions_helper' => ['services', 'ui_extensions_helper', 'getUiExtensionsHelperService', true],
            'url_generator' => ['services', 'url_generator', 'getUrlGeneratorService', false],
        ], [
            'brick_collection' => '?',
            'brick_controller_helper' => '?',
            'browse_brick' => '?',
            'context_manipulator' => '?',
            'http_kernel' => '?',
            'lifecycle_validator' => '?',
            'navigation_rule_helper' => '?',
            'object_form_handler' => '?',
            'parameter_bag' => '?',
            'request_manipulator' => '?',
            'request_stack' => '?',
            'router' => '?',
            'scope_validator' => '?',
            'security_helper' => '?',
            'session' => '.session.deprecated',
            'session_message_helper' => '?',
            'twig' => '?',
            'ui_extensions_helper' => '?',
            'url_generator' => '?',
        ]);
    }
}
