<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_AppService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'cache.app' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\FilesystemAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/psr/cache/src/CacheItemPoolInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache-contracts/CacheInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/psr/log/Psr/Log/LoggerAwareInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/ResettableInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/psr/log/Psr/Log/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Traits/AbstractAdapterTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache-contracts/CacheTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Traits/ContractsTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Adapter/AbstractAdapter.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/PruneableInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Traits/FilesystemCommonTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Traits/FilesystemTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Adapter/FilesystemAdapter.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Marshaller/MarshallerInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Marshaller/DefaultMarshaller.php';

        $container->services['cache.app'] = $instance = new \Symfony\Component\Cache\Adapter\FilesystemAdapter('nFzPg8-Nr6', 0, ($container->targetDir.''.'/pools/app'), new \Symfony\Component\Cache\Marshaller\DefaultMarshaller(NULL, false));

        $instance->setLogger(($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));

        return $instance;
    }
}
