<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_SystemService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'cache.system' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\AdapterInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/psr/cache/src/CacheItemPoolInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache-contracts/CacheInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/psr/log/Psr/Log/LoggerAwareInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/ResettableInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/psr/log/Psr/Log/LoggerAwareTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Traits/AbstractAdapterTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache-contracts/CacheTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Traits/ContractsTrait.php';
        include_once \dirname(__DIR__, 5).'/lib/symfony/cache/Adapter/AbstractAdapter.php';

        return $container->services['cache.system'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('SsyAgwbaPl', 0, $container->getParameter('container.build_id'), ($container->targetDir.''.'/pools/system'), ($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
    }
}
