<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCombodo_CurrentContact_PhotoUrlService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'combodo.current_contact.photo_url' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\VariableAccessor\CombodoCurrentContactPhotoUrl
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/VariableAccessor/CombodoCurrentContactPhotoUrl.php';

        return $container->services['combodo.current_contact.photo_url'] = new \Combodo\iTop\Portal\VariableAccessor\CombodoCurrentContactPhotoUrl(($container->privates['Combodo\\iTop\\Portal\\EventListener\\UserProvider'] ?? $container->getUserProviderService()), $container, $container->getEnv('string:COMBODO_PORTAL_BASE_ABSOLUTE_URL'));
    }
}
