<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionListenerService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the private 'Combodo\iTop\Portal\EventListener\ExceptionListener' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\EventListener\ExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/EventListener/ExceptionListener.php';

        $container->privates['Combodo\\iTop\\Portal\\EventListener\\ExceptionListener'] = $instance = new \Combodo\iTop\Portal\EventListener\ExceptionListener();

        $instance->setContainer($container);

        return $instance;
    }
}
