<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavigationRuleHelperService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'navigation_rule_helper' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Helper\NavigationRuleHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/Helper/NavigationRuleHelper.php';

        return $container->services['navigation_rule_helper'] = new \Combodo\iTop\Portal\Helper\NavigationRuleHelper(($container->services['ModuleDesign'] ?? ($container->services['ModuleDesign'] = new \ModuleDesign($container->getEnv('string:PORTAL_ID')))), ($container->services['url_generator'] ?? $container->getUrlGeneratorService()), ($container->services['brick_collection'] ?? $container->load('getBrickCollectionService')), ($container->services['scope_validator'] ?? $container->load('getScopeValidatorService')));
    }
}
