<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectFormHandlerService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'object_form_handler' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Helper\ObjectFormHandlerHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/Helper/ObjectFormHandlerHelper.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/Twig/AppExtension.php';

        return $container->services['object_form_handler'] = new \Combodo\iTop\Portal\Helper\ObjectFormHandlerHelper(($container->services['request_manipulator'] ?? $container->load('getRequestManipulatorService')), ($container->services['context_manipulator'] ?? $container->load('getContextManipulatorService')), ($container->services['navigation_rule_helper'] ?? $container->load('getNavigationRuleHelperService')), ($container->services['scope_validator'] ?? $container->load('getScopeValidatorService')), ($container->services['security_helper'] ?? $container->load('getSecurityHelperService')), ($container->services['url_generator'] ?? $container->getUrlGeneratorService()), $container->parameters['combodo.portal.instance.conf'], $container->getEnv('string:PORTAL_ID'), ($container->privates['Combodo\\iTop\\Portal\\Twig\\AppExtension'] ?? ($container->privates['Combodo\\iTop\\Portal\\Twig\\AppExtension'] = new \Combodo\iTop\Portal\Twig\AppExtension())));
    }
}
