<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestManipulatorService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'request_manipulator' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Helper\RequestManipulatorHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/Helper/RequestManipulatorHelper.php';

        return $container->services['request_manipulator'] = new \Combodo\iTop\Portal\Helper\RequestManipulatorHelper(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
