<?php

namespace ContainerOApJeBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityHelperService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'security_helper' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Helper\SecurityHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/env-production/itop-portal-base/portal/src/Helper/SecurityHelper.php';

        return $container->services['security_helper'] = new \Combodo\iTop\Portal\Helper\SecurityHelper(($container->services['scope_validator'] ?? $container->load('getScopeValidatorService')), ($container->services['lifecycle_validator'] ?? $container->load('getLifecycleValidatorService')), false);
    }
}
